---
version: '3'

# using fixed ip addresses so opennms config works
# to see all netowrk use docker network ls
# to see config use docker network inspect minimal-minion-kafka_frontend
# note gateway is 172.20.0.1 
networks:
  frontend:
    ipam:
      config:
        - subnet: 172.20.0.0/24


services:

# stand alone karaf container 
  karaf1:
    image: ${DOCKER_REGISTRY:-docker.io}/apache/karaf:4.3.6
    container_name: karaf1
    hostname: karaf1
    expose:
      - "1099"
      - "44444"
      - "8101"
      - "8181"
      - "9090" # only used for camel http examples
    ports:
      - "18101:8101"
      - "11099:1099"
      - "34444:44444"
      - "18181:8181"
      - "55555:55555"
      - "9090:9090"
    volumes:
      - ~/.m2:/root/.m2
      - ./karaf1/etc/custom.system.properties:/opt/apache-karaf/etc/custom.system.properties
      - ./karaf1/etc/users.properties:/opt/apache-karaf/etc/users.properties
      - ./karaf1/etc/org.ops4j.pax.logging.cfg:/opt/apache-karaf/etc/org.ops4j.pax.logging.cfg
      - ./karaf1/etc/org.ops4j.pax.url.mvn.cfg:/opt/apache-karaf/etc/org.ops4j.pax.url.mvn.cfg
      - ./karaf1/deploy:/opt/apache-karaf/deploy
      - ./karaf1/lib/boot/pax-exam-container-rbc-onms-4.13.5.jar:/opt/apache-karaf/lib/boot/pax-exam-container-rbc-onms-4.13.5.jar
      - ./karaf1/lib/boot/pax-exam-4.13.5.jar:/opt/apache-karaf/lib/boot/pax-exam-4.13.5.jar
      - ./karaf1/lib/boot/opennms-paxexam-rmi-server-0.0.1-SNAPSHOT.jar:/opt/apache-karaf/lib/boot/opennms-paxexam-rmi-server-0.0.1-SNAPSHOT.jar
      - ./karaf1/misc:/misc
    command: karaf
    stdin_open: true
    tty: true
    networks:
      frontend:
        ipv4_address: 172.20.0.8